allitems = [
    '',
    'Magic Meter',
    'Double Defense',
    'Slingshot',
    'Boomerang',
    'Bow',
    'Bomb Bag',
    'Progressive Hookshot',
    'Progressive Strength Upgrade',
    'Progressive Scale',
    'Hammer',
    'Iron Boots',
    'Hover Boots',
    'Kokiri Sword',
    'Biggoron Sword',
    'Master Sword',
    'Deku Shield',
    'Hylian Shield',
    'Mirror Shield',
    'Farores Wind',
    'Nayrus Love',
    'Dins Fire',
    'Fire Arrows',
    'Ice Arrows',
    'Light Arrows',
    'Lens of Truth',
    'Ocarina',
    'Goron Tunic',
    'Zora Tunic',
    'Epona',
    'Zeldas Lullaby',
    'Eponas Song',
    'Sarias Song',
    'Suns Song',
    'Song of Time',
    'Song of Storms',
    'Minuet of Forest',
    'Bolero of Fire',
    'Serenade of Water',
    'Requiem of Spirit',
    'Nocturne of Shadow',
    'Prelude of Light',
    'Bottle',
    'Bottle with Letter',
    'Bottle with Milk',
    'Bottle with Red Potion',
    'Bottle with Green Potion',
    'Bottle with Blue Potion',
    'Bottle with Fairy',
    'Bottle with Fish',
    'Bottle with Blue Fire',
    'Bottle with Bugs',
    'Bottle with Poe',
    'Bottle with Big Poe',
    'Stone of Agony',
    'Gerudo Membership Card',
    'Progressive Wallet',
    'Deku Stick Capacity',
    'Deku Nut Capacity',
    'Heart Container',
    'Piece of Heart',
    'Piece of Heart (Treasure Chest Game)',
    'Recovery Heart',
    'Rupee (Treasure Chest Game)',
    'Deku Stick (1)',
    'Rupee (1)',
    'Rupees (5)',
    'Rupees (20)',
    'Rupees (50)',
    'Rupees (200)',
    'Weird Egg',
    'Zeldas Letter',
    'Pocket Egg',
    'Pocket Cucco',
    'Cojiro',
    'Odd Mushroom',
    'Odd Potion',
    'Poachers Saw',
    'Broken Sword',
    'Prescription',
    'Eyeball Frog',
    'Eyedrops',
    'Claim Check',
    'Map',
    'Compass',
    'BossKey',
    'SmallKey',
    'FortressSmallKey',
    'KeyError',
    'Arrows (5)',
    'Arrows (10)',
    'Arrows (30)',
    'Bombs (5)',
    'Bombs (10)',
    'Bombs (20)',
    'Ice Trap',
    'Magic Bean',
    'Bombchus',
    'Bombchus (5)',
    'Bombchus (10)',
    'Bombchus (20)',
    'Deku Nuts (5)',
    'Deku Nuts (10)',
    'Deku Seeds (30)',
    'Gold Skulltula Token'
]

items = [
    '',
    'Useless',
    'Magic Meter',
    'Slingshot',
    'Boomerang',
    'Bow',
    'Bomb Bag',
    'Progressive Hookshot',
    'Progressive Strength Upgrade',
    'Progressive Scale',
    'Hammer',
    'Iron Boots',
    'Hover Boots',
    'Mirror Shield',
    'Dins Fire',
    'Fire Arrows',
    'Light Arrows',
    'Lens of Truth',
    'Ocarina',
    'Goron Tunic',
    'Zora Tunic',
    'Zeldas Lullaby',
    'Eponas Song',
    'Sarias Song',
    'Suns Song',
    'Song of Time',
    'Song of Storms',
    'Minuet of Forest',
    'Bolero of Fire',
    'Serenade of Water',
    'Requiem of Spirit',
    'Nocturne of Shadow',
    'Prelude of Light',
    'Bottle',
    'Bottle with Letter',
    'Stone of Agony',
    'Gerudo Membership Card',
    'Progressive Wallet',
    'Pocket Egg',
    'Pocket Cucco',
    'Cojiro',
    'Odd Mushroom',
    'Odd Potion',
    'Poachers Saw',
    'Broken Sword',
    'Prescription',
    'Eyeball Frog',
    'Eyedrops',
    'Claim Check',
    'Map',
    'Compass',
    'BossKey',
    'SmallKey',
    'FortressSmallKey',
    'Bombchus'
]