locations = [
    "",
    "Kokiri Forest",
    "Lost Wood",
    "Hyrule Field",
    "Kakariko Village",
    "Graveyard",
    "Death Montain Tail",
    "Goron City",
    "Death Montain Crater",
    "Sacred Forest Meadow",
    "Market",
    "Hyrule Castle",
    "Ganon Castle",
    "Ranch Lon Lon",
    "Hylia Lake",
    "Gerudo Valley",
    "Gerudo Fortress",
    "Haunted Wasteland",
    "Desert Colossus",
    "Zora's River",
    "Zora's Domain",
    "Zora's Fountain",
    "Deku Tree",
    "Dodongo's Cavern",
    "Jabu-Jabu's Belly",
    "Forest Temple",
    "Water Temple",
    "Fire Temple",
    "Shadow Temple",
    "Spirit Temple",
    "Temple of Time",
    "Ice Cavern",
    "Bottom of the Well",
    "Outside Ganon Castle",
    "Gerudo Training Ground",
]