locations = [
    "",
    "Kokiri Forest",
    "Lost Wood",
    "Hyrule Field",
    "Kakariko Village",
    "Graveyard",
    "Death Montain Tail",
    "Goron City",
    "Death Montain Crater",
    "Sacred Forest Meadow",
    "Market",
    "Hyrule Castle",
    "Ganon Castle",
    "Ranch Lon Lon",
    "Hylia Lake",
    "Gerudo Valley",
    "Gerudo Fortress",
    "Haunted Wasteland",
    "Deset Colossus",
    "Zora's River",
    "Zora's Domain",
    "Zora's Fountain",
    "Inside the Deku Tree",
    "Dodongo's Cavern",
    "Inside Jabu-Jabu's Belly",
    "Forest Temple",
    "Water Temple",
    "Fire Temple",
    "Shadow Temple",
    "Spirit Temple",
    "Ice Cavern",
    "Bottom of the Well"
]